// Design and images
// Libraries
import Head from "next/head";
// Components
import Hero from "@/components/Hero";
import Venue from "@/components/Venue";
import Price from "@/components/Price";
import Cta from "@/components/Cta";
import About from "@/components/About";
import Images from "@/components/Images";
// Outside data

/////////////////////////////

export default function Home() {
  return (
    <>
      <Head>
        <title>Preston City Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden ">
        <Hero />
        <About />
        <Images />
        <Price />
        <Venue />
      </main>
    </>
  );
}
